-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2025-06-06 10:28:53 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE ssx_alertas CASCADE CONSTRAINTS;

DROP TABLE ssx_emails CASCADE CONSTRAINTS;

DROP TABLE ssx_enderecos CASCADE CONSTRAINTS;

DROP TABLE ssx_itens_pedido CASCADE CONSTRAINTS;

DROP TABLE ssx_leituras_sensores CASCADE CONSTRAINTS;

DROP TABLE ssx_pedidos CASCADE CONSTRAINTS;

DROP TABLE ssx_produtos CASCADE CONSTRAINTS;

DROP TABLE ssx_pulseira_request CASCADE CONSTRAINTS;

DROP TABLE ssx_sensores CASCADE CONSTRAINTS;

DROP TABLE ssx_usuarios CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ssx_alertas (
    id_alerta                  INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_ltrs_id_leitura_sensor INTEGER NOT NULL,
    tipo_alerta                VARCHAR2(16) NOT NULL,
    mensagem                   VARCHAR2(50) NOT NULL,
    nivel_risco                INTEGER NOT NULL,
    status                     VARCHAR2(15) NOT NULL
);

ALTER TABLE ssx_alertas ADD CHECK ( nivel_risco BETWEEN 1 AND 3 );

ALTER TABLE ssx_alertas
    ADD CHECK ( status IN ( 'ATIVO', 'RESOLVIDO', 'IGNORADO' ) );

CREATE UNIQUE INDEX ssx_alertas__idx ON
    ssx_alertas (
        ssx_ltrs_id_leitura_sensor
    ASC );

ALTER TABLE ssx_alertas ADD CONSTRAINT ssx_alertas_pk PRIMARY KEY ( id_alerta );

CREATE TABLE ssx_emails (
    id_email INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    email    VARCHAR2(255) NOT NULL,
    ativo    CHAR(1) NOT NULL
);

ALTER TABLE ssx_emails ADD CONSTRAINT ssx_emails_pk PRIMARY KEY ( id_email );

CREATE TABLE ssx_enderecos (
    id_endereco             INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_usuarios_id_usuario INTEGER NOT NULL,
    cep                     VARCHAR2(9) NOT NULL,
    estado                  VARCHAR2(20) NOT NULL,
    cidade                  VARCHAR2(30) NOT NULL,
    bairro                  VARCHAR2(50) NOT NULL,
    logradouro              VARCHAR2(60) NOT NULL
);

ALTER TABLE ssx_enderecos ADD CONSTRAINT ssx_enderecos_pk PRIMARY KEY ( id_endereco );

CREATE TABLE ssx_itens_pedido (
    id_item_pedido          INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_usuarios_id_usuario INTEGER NOT NULL,
    ssx_pedidos_id_pedido   INTEGER NOT NULL,
    quantidade              INTEGER NOT NULL
);

ALTER TABLE ssx_itens_pedido ADD CONSTRAINT ssx_itens_pedido_pk PRIMARY KEY ( id_item_pedido );

CREATE TABLE ssx_leituras_sensores (
    id_leitura_sensor       INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_usuarios_id_usuario INTEGER NOT NULL,
    temperatura             NUMBER NOT NULL,
    umidade                 NUMBER NOT NULL,
    radiacao                NUMBER NOT NULL,
    data_hora               TIMESTAMP NOT NULL
);

ALTER TABLE ssx_leituras_sensores ADD CONSTRAINT ssx_leituras_sensores_pk PRIMARY KEY ( id_leitura_sensor );

CREATE TABLE ssx_pedidos (
    id_pedido   INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    data_pedido DATE NOT NULL,
    preco       NUMBER NOT NULL,
    status      VARCHAR2(15) NOT NULL
);

ALTER TABLE ssx_pedidos
    ADD CHECK ( status IN ( 'CARRINHO', 'PAGO', 'A CAMINHO', 'ENTREGUE', 'CANCELADO' ) );

ALTER TABLE ssx_pedidos ADD CONSTRAINT ssx_pedidos_pk PRIMARY KEY ( id_pedido );

CREATE TABLE ssx_produtos (
    id_produto            INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_ip_id_item_pedido INTEGER NOT NULL,
    nome                  VARCHAR2(20) NOT NULL,
    descricao             VARCHAR2(50) NOT NULL,
    preco_unitario        NUMBER NOT NULL
);

ALTER TABLE ssx_produtos ADD CONSTRAINT ssx_produtos_pk PRIMARY KEY ( id_produto );

CREATE TABLE ssx_pulseira_request (
    id_pulseira_request     INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_usuarios_id_usuario INTEGER NOT NULL,
    device_token            VARCHAR2(18) NOT NULL
);

ALTER TABLE ssx_pulseira_request ADD CONSTRAINT ssx_pulseira_request_pk PRIMARY KEY ( id_pulseira_request );

CREATE TABLE ssx_sensores (
    id_sensor               INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_produtos_id_produto INTEGER NOT NULL,
    tipo                    VARCHAR2(12) NOT NULL,
    descricao               VARCHAR2(40) NOT NULL,
    modelo                  VARCHAR2(20) NOT NULL,
    status                  VARCHAR2(15) NOT NULL
);

ALTER TABLE ssx_sensores ADD CONSTRAINT ssx_sensores_pk PRIMARY KEY ( id_sensor );

CREATE TABLE ssx_usuarios (
    id_usuario          INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
    ssx_emails_id_email INTEGER NOT NULL,
    nome                VARCHAR2(60) NOT NULL,
    senha               VARCHAR2(60) NOT NULL,
    role                VARCHAR2(10) NOT NULL
);

ALTER TABLE ssx_usuarios
    ADD CHECK ( role IN ( 'ADMIN', 'USER' ) );

CREATE UNIQUE INDEX ssx_usuarios__idx ON
    ssx_usuarios (
        ssx_emails_id_email
    ASC );

ALTER TABLE ssx_usuarios ADD CONSTRAINT ssx_usuarios_pk PRIMARY KEY ( id_usuario );

ALTER TABLE ssx_alertas
    ADD CONSTRAINT ssx_alertas_ssx_ltrs_fk FOREIGN KEY ( ssx_ltrs_id_leitura_sensor )
        REFERENCES ssx_leituras_sensores ( id_leitura_sensor );

ALTER TABLE ssx_enderecos
    ADD CONSTRAINT ssx_enderecos_ssx_usuarios_fk FOREIGN KEY ( ssx_usuarios_id_usuario )
        REFERENCES ssx_usuarios ( id_usuario );

ALTER TABLE ssx_itens_pedido
    ADD CONSTRAINT ssx_itens_pedido_pedidos_fk FOREIGN KEY ( ssx_pedidos_id_pedido )
        REFERENCES ssx_pedidos ( id_pedido );

ALTER TABLE ssx_itens_pedido
    ADD CONSTRAINT ssx_itens_pedido_usuarios_fk FOREIGN KEY ( ssx_usuarios_id_usuario )
        REFERENCES ssx_usuarios ( id_usuario );

ALTER TABLE ssx_leituras_sensores
    ADD CONSTRAINT ssx_ltrs_ssx_usuarios_fk FOREIGN KEY ( ssx_usuarios_id_usuario )
        REFERENCES ssx_usuarios ( id_usuario );

ALTER TABLE ssx_produtos
    ADD CONSTRAINT ssx_produtos_ssx_ip_fk FOREIGN KEY ( ssx_ip_id_item_pedido )
        REFERENCES ssx_itens_pedido ( id_item_pedido );

ALTER TABLE ssx_pulseira_request
    ADD CONSTRAINT ssx_puls_req_ssx_usuarios_fk FOREIGN KEY ( ssx_usuarios_id_usuario )
        REFERENCES ssx_usuarios ( id_usuario );

ALTER TABLE ssx_sensores
    ADD CONSTRAINT ssx_sensores_ssx_produtos_fk FOREIGN KEY ( ssx_produtos_id_produto )
        REFERENCES ssx_produtos ( id_produto );

ALTER TABLE ssx_usuarios
    ADD CONSTRAINT ssx_usuarios_ssx_emails_fk FOREIGN KEY ( ssx_emails_id_email )
        REFERENCES ssx_emails ( id_email );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             2
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
